
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Starter Template for Bootstrap</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="/css/min.css" />

    <?php echo $this->headLink()->appendStylesheet($this->baseUrl.'/css/main.css');?>
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>

<body>

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">

    <a class="navbar-brand" href="#">Do it!</a>
</nav>

<div class="container">

    <div>
        <div class="history_data">
            <?php
                echo $this->partialLoop('partials/history.phtml', $this->history);
            ?>
        </div>
        <select name="cur_from" class="cur_from">
            <?php

                echo $this->partialLoop('partials/currencies.phtml', $this->currencies);
            ?>
        </select>
        <input type="number" class="from_count" />


        <span>To</span>

        <input type="number" class="res" />

        <select name="cur_to" class="cur_to">
            <?php

                echo $this->partialLoop('partials/currencies.phtml', $this->currencies);
            ?>
        </select>

        <button class="btn btn-primary send">Go</button>
    </div>
    <div class="error_message">
        <span></span>
    </div>

</div>




<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<?php echo $this->headScript()
    ->appendFile($this->baseUrl().'/js/main.js');?>
</body>
</html>







